### ISSUE TITLE
Hardcoded icons

### ISSUE THREAD

**Issue by bilelmoussaoui** [muflone/gnome-appfolders-manager#2]
The application won't show an icon if the application has a hardcoded icon path, for example Viber or Slack
![capture du 2016-05-24 01-21-03](https://cloud.githubusercontent.com/assets/7660997/15487462/d2d22d22-214d-11e6-8e10-20cf69aba124.png)

**Comment by muflone** [comment]
This issue was already fixed in the git version with the commit 9bf1bcdcf9263fb63edc288527014d6127114e1d
It will be included in the release 0.3.0, thank you

**Comment by muflone** [comment]
Fixed and released

**Comment by bilelmoussaoui** [comment]
Still does not work perfectly, if the icon name is `viber.png` the application does not detect it. I think you should only use `path.splitext(icon_name)[0]` instead of the icon name :)

**Comment by muflone** [comment]
I can see the viber icon in the applications list.
![schermata da 2016-05-29 10-54-56](https://cloud.githubusercontent.com/assets/1284163/15632245/d9861f42-258b-11e6-8746-1d4dd53b2a83.png)

What version of GNOME App Folders Manager are you using?
What linux distribution?
Where in the file system is located the viber.png file?

**Comment by bilelmoussaoui** [comment]
It's not the case here :( 
![capture du 2016-06-01 23-31-59](https://cloud.githubusercontent.com/assets/7660997/15726413/12559c0e-2851-11e6-8fb7-b176a5b77356.png)

I'm using Gnome 3.20.6 on Archlinux with the latest version of the application (0.3 i suppose)
The content of the desktop file is 

```
[Desktop Entry]
Name=Viber
Comment=Viber VoIP and messenger
Exec=viber
Icon=viber.png
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Network;Application;InstantMessaging;
Path=
```

The icon is correctly shown on Gnome shell

**Comment by muflone** [comment]
I think I've found the source of the issue.
Can you temporarily switch to the default GNOME Shell adwaita theme and restart the program?

**Comment by bilelmoussaoui** [comment]
the same result with Adwaita theme
![capture d ecran de 2016-06-02 00-33-42](https://cloud.githubusercontent.com/assets/7660997/15727921/b9b52b24-2859-11e6-89db-f5e324a11627.png)

**Comment by muflone** [comment]
I thinks there's a bug on the images loading.
Could you please remove the viber application from the appfolder and add it again? It should be visible until you restart.

**Comment by bilelmoussaoui** [comment]
Well it works in the adding window 
![capture du 2016-06-02 00-50-00](https://cloud.githubusercontent.com/assets/7660997/15728303/ff58853e-285b-11e6-9596-f97ccfe2f05c.png)
Once it's added it still works
![capture du 2016-06-02 00-50-38](https://cloud.githubusercontent.com/assets/7660997/15728315/11fbee06-285c-11e6-82da-c1ad8353d1ce.png)
And when i restart the application or change the directory it does not work anymore

**Comment by muflone** [comment]
Ok I got it.
I'll fix it as soon as possible.
thank you

**Comment by muflone** [comment]
this issue should be solved in version 0.3.2
